

modLoader="javafml"


loaderVersion="[28,)"


issueTrackerURL="http://my.issue.tracker/"


[[mods]]

modId="testmod"

version="${1.0}"

displayName="TestMod"

updateJSONURL="http://myurl.me/"

displayURL="http://example.com/"

logoFile="examplemod.png"

credits="To all the people out there looking at this!"

authors="Drizzs"


description='''

This is a test mod for testing purposes

'''
